# Generated by Django 5.1 on 2024-08-27 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("videos", "0002_video_thumbnail_file"),
    ]

    operations = [
        migrations.AddField(
            model_name="video",
            name="apply_ascii_filter",
            field=models.BooleanField(default=False),
        ),
    ]
