version: "3.8"

services:
  postgres:
    image: postgres:15.6
    restart: always
    volumes:
      - /opt/youtube-nano/postgres/:/var/lib/postgresql/data/
    ports:
      - "15432:5432"
    environment:
      - POSTGRES_DB=youtube-nano
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
  django:
    build: .
    restart: always
    command: python /app/manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    env_file:
       - ./app/.env
    depends_on:
      - postgres
